spring.application.name=spa

#database
spring.datasource.url=jdbc:h2:mem:mydb;INIT=CREATE SCHEMA IF NOT EXISTS interview
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.default_schema=interview

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#security
jwt.secret=my-super-secure-secret-key-123456789012